### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by fpedroza** [mixpanel/mixpanel-node#160]
Picked up the new version today (0.11) and am now seeing this error at app startup:
```
/<PATH>/server/node_modules/mixpanel/lib/mixpanel-node.js:43
        config: {...DEFAULT_CONFIG},
                 ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Object.obj.(anonymous function) [as runInThisContext] (/Users/pedrozaf/.nvm/versions/node/v6.17.1/lib/node_modules/node-dev/lib/hook.js:30:19)
    at Module._compile (module.js:549:28)
    at Module._extensions..js (module.js:586:10)
    at Object.nodeDevHook [as .js] (/Users/pedrozaf/.nvm/versions/node/v6.17.1/lib/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
```

**Comment by tdumitrescu** [comment]
It looks like you're running on Node 6.17, which is no longer supported by this SDK; Node 6 in general reached End Of Life on April 30, 2019 after the end of its Maintenance phase. To use new versions of the SDK you'll probably want to upgrade at least to Node 10 (as even 8 is reaching EOL in January 2020).
